spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/koi
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: false
    open-in-view: false
  main:
    banner-mode: off